language: csharp
sudo: required
dist: trusty
addons:
  chrome: stable

before_install:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - curl -o dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.300/dotnet-sdk-2.1.300-linux-x64.tar.gz
  - sudo mkdir -p /usr/share/dotnet
  - sudo tar -zxf dotnet.tar.gz -C /usr/share/dotnet
  - sudo ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: latest
os:
  - linux

script:
  - ./build.sh